-- Sheet 1
CREATE TABLE [dbo].[BuildingData] (
    [BLDG_ID] INT NOT NULL,
    [CLLI] NVARCHAR(20) NULL,
    [Address] NVARCHAR(255) NULL,
    [City] NVARCHAR(100) NULL,
    [State] CHAR(2) NULL,
    [Zip] VARCHAR(10) NULL,
    [LATITUDE] DECIMAL(9,6) NULL,
    [LONGITUDE] DECIMAL(9,6) NULL,
    [Lumen_Fiber_Connected] NVARCHAR(255) NULL,
    [Ethernet_Transport_Enabled] NVARCHAR(255) NULL,
    [Wave_Transport_Enabled] NVARCHAR(255) NULL,
    [Tenant_Count] INT NULL,
    [Customer_Count] INT NULL,
    [Annual_Customer_Revenue] DECIMAL(18,2) NULL,
    [TOTAL_ANNUAL_REVENUE_POTENTIAL] DECIMAL(18,2) NULL,
    [FIBER_BUILD_COST] DECIMAL(18,2) NULL,
    [Market] NVARCHAR(50) NULL
);

-- Sheet 2
CREATE TABLE [dbo].[DallasToWashingtonILAData] (
    [ILA ID] INT NOT NULL,
    [WAVE_BANDWIDTH_CAPABILITY] NVARCHAR(100) NULL,
    [TOTAL_CONDUITS] INT NULL,
    [CONDUITS_IN_USE] INT NULL,
    [CONDUITS_FREE] INT NULL,
    [TOTAL COMMERCIAL POWER (KW)] INT NULL,
    [UTILIZED COMMERCIAL FIBER (KW)] INT NULL,
    [TOTAL SHELTERS] INT NULL,
    [TOTAL_FIBERS] INT NULL,
    [UTILIZED_FIBERS] INT NULL,
    [SPARE_FIBERS] INT NULL,
    [TOTAL NUMBER OF RACKS] INT NULL,
    [USED_RACKS] INT NULL,
    [FREE_RACKS] INT NULL
);

-- Sheet 3
CREATE TABLE [dbo].[SalesQuotingData] (
    [Customer_ID] INT NOT NULL,
    [SALES_CHANNEL] NVARCHAR(50) NULL,
    [QUOTE_STAGE] NVARCHAR(255) NULL,
    [QUOTED_MONTH_YEAR] DATE NULL,
    [CONTRACT_LENGTH_QTY] INT NULL,
    [QUOTE_ID] NVARCHAR(50) NOT NULL,
    [SOLUTION_ID] NVARCHAR(50) NULL,
    [BANDWIDTH] NVARCHAR(100) NULL,
    [PRODUCT] NVARCHAR(100) NULL,
    [MONTHLY RECURRING REVENUE] DECIMAL(18,2) NULL,
    [NON-RECURRING REVENUE] DECIMAL(18,2) NULL,
    [ADDRESS] NVARCHAR(255) NULL,
    [CITY] NVARCHAR(100) NULL,
    [STATE] CHAR(2) NULL,
    [BLDG_ID] INT NOT NULL
);

BULK INSERT dbo.BuildingData
FROM 'C:\Users\jomck\Downloads\BuildingData.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n',
    TABLOCK
);


BULK INSERT dbo.DallasToWashingtonILAData
FROM 'C:\Users\jomck\Downloads\DallasToWashingtonILAData.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n',
    TABLOCK
);

BULK INSERT dbo.SalesQuotingData
FROM 'C:\Users\jomck\Downloads\SalesQuotingData.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n',
    TABLOCK
);

--- Building Data Nulls
SELECT
    COUNT(*) AS total_rows,
    SUM(CASE WHEN BLDG_ID IS NULL THEN 1 ELSE 0 END) AS BLDG_ID_nulls,
    SUM(CASE WHEN CLLI IS NULL OR CLLI = '' THEN 1 ELSE 0 END) AS CLLI_nulls,
    SUM(CASE WHEN Address IS NULL OR Address = '' THEN 1 ELSE 0 END) AS Address_nulls,
    SUM(CASE WHEN City IS NULL OR City = '' THEN 1 ELSE 0 END) AS City_nulls,
    SUM(CASE WHEN State IS NULL OR State = '' THEN 1 ELSE 0 END) AS State_nulls,
    SUM(CASE WHEN Zip IS NULL OR Zip = '' THEN 1 ELSE 0 END) AS Zip_nulls,
    SUM(CASE WHEN LATITUDE IS NULL THEN 1 ELSE 0 END) AS LATITUDE_nulls,
    SUM(CASE WHEN LONGITUDE IS NULL THEN 1 ELSE 0 END) AS LONGITUDE_nulls,
    SUM(CASE WHEN Lumen_Fiber_Connected IS NULL OR Lumen_Fiber_Connected = '' THEN 1 ELSE 0 END) AS LumenFiber_nulls,
    SUM(CASE WHEN Ethernet_Transport_Enabled IS NULL OR Ethernet_Transport_Enabled = '' THEN 1 ELSE 0 END) AS Ethernet_nulls,
    SUM(CASE WHEN Wave_Transport_Enabled IS NULL OR Wave_Transport_Enabled = '' THEN 1 ELSE 0 END) AS Wave_nulls,
    SUM(CASE WHEN Tenant_Count IS NULL THEN 1 ELSE 0 END) AS TenantCount_nulls,
    SUM(CASE WHEN Customer_Count IS NULL THEN 1 ELSE 0 END) AS CustomerCount_nulls,
    SUM(CASE WHEN Annual_Customer_Revenue IS NULL THEN 1 ELSE 0 END) AS AnnualRev_nulls,
    SUM(CASE WHEN TOTAL_ANNUAL_REVENUE_POTENTIAL IS NULL THEN 1 ELSE 0 END) AS Potential_nulls,
    SUM(CASE WHEN FIBER_BUILD_COST IS NULL THEN 1 ELSE 0 END) AS FiberBuildCost_nulls,
    SUM(CASE WHEN Market IS NULL OR Market = '' THEN 1 ELSE 0 END) AS Market_nulls
FROM dbo.BuildingData;

--- SalesQuotiongData
SELECT
    COUNT(*) AS total_rows,
    SUM(CASE WHEN Customer_ID IS NULL THEN 1 ELSE 0 END) AS CustomerID_nulls,
    SUM(CASE WHEN SALES_CHANNEL IS NULL OR SALES_CHANNEL = '' THEN 1 ELSE 0 END) AS SalesChannel_nulls,
    SUM(CASE WHEN QUOTE_STAGE IS NULL OR QUOTE_STAGE = '' THEN 1 ELSE 0 END) AS QuoteStage_nulls,
    SUM(CASE WHEN QUOTED_MONTH_YEAR IS NULL THEN 1 ELSE 0 END) AS QuoteDate_nulls,
    SUM(CASE WHEN CONTRACT_LENGTH_QTY IS NULL THEN 1 ELSE 0 END) AS ContractLength_nulls,
    SUM(CASE WHEN QUOTE_ID IS NULL OR QUOTE_ID = '' THEN 1 ELSE 0 END) AS QuoteID_nulls,
    SUM(CASE WHEN SOLUTION_ID IS NULL OR SOLUTION_ID = '' THEN 1 ELSE 0 END) AS SolutionID_nulls,
    SUM(CASE WHEN BANDWIDTH IS NULL OR BANDWIDTH = '' THEN 1 ELSE 0 END) AS Bandwidth_nulls,
    SUM(CASE WHEN PRODUCT IS NULL OR PRODUCT = '' THEN 1 ELSE 0 END) AS Product_nulls,
    SUM(CASE WHEN [MONTHLY RECURRING REVENUE] IS NULL THEN 1 ELSE 0 END) AS MRR_nulls,
    SUM(CASE WHEN [NON-RECURRING REVENUE] IS NULL THEN 1 ELSE 0 END) AS NRR_nulls,
    SUM(CASE WHEN ADDRESS IS NULL OR ADDRESS = '' THEN 1 ELSE 0 END) AS Address_nulls,
    SUM(CASE WHEN CITY IS NULL OR CITY = '' THEN 1 ELSE 0 END) AS City_nulls,
    SUM(CASE WHEN STATE IS NULL OR STATE = '' THEN 1 ELSE 0 END) AS State_nulls,
    SUM(CASE WHEN BLDG_ID IS NULL THEN 1 ELSE 0 END) AS BldgID_nulls
FROM dbo.SalesQuotingData;

--DallasToWashingtonILAData
SELECT
    COUNT(*) AS total_rows,
    SUM(CASE WHEN [ILA ID] IS NULL THEN 1 ELSE 0 END) AS ILAID_nulls,
    SUM(CASE WHEN [WAVE_BANDWIDTH_CAPABILITY] IS NULL OR [WAVE_BANDWIDTH_CAPABILITY] = '' THEN 1 ELSE 0 END) AS WaveCapability_nulls,
    SUM(CASE WHEN [TOTAL_CONDUITS] IS NULL THEN 1 ELSE 0 END) AS TotalConduits_nulls,
    SUM(CASE WHEN [CONDUITS_IN_USE] IS NULL THEN 1 ELSE 0 END) AS ConduitsInUse_nulls,
    SUM(CASE WHEN [CONDUITS_FREE] IS NULL THEN 1 ELSE 0 END) AS ConduitsFree_nulls,
    SUM(CASE WHEN [TOTAL COMMERCIAL POWER (KW)] IS NULL THEN 1 ELSE 0 END) AS TotalPower_nulls,
    SUM(CASE WHEN [UTILIZED COMMERCIAL FIBER (KW)] IS NULL THEN 1 ELSE 0 END) AS UtilizedPower_nulls,
    SUM(CASE WHEN [TOTAL SHELTERS] IS NULL THEN 1 ELSE 0 END) AS TotalShelters_nulls,
    SUM(CASE WHEN [TOTAL_FIBERS] IS NULL THEN 1 ELSE 0 END) AS TotalFibers_nulls,
    SUM(CASE WHEN [UTILIZED_FIBERS] IS NULL THEN 1 ELSE 0 END) AS UtilizedFibers_nulls,
    SUM(CASE WHEN [SPARE_FIBERS] IS NULL THEN 1 ELSE 0 END) AS SpareFibers_nulls,
    SUM(CASE WHEN [TOTAL NUMBER OF RACKS] IS NULL THEN 1 ELSE 0 END) AS TotalRacks_nulls,
    SUM(CASE WHEN [USED_RACKS] IS NULL THEN 1 ELSE 0 END) AS UsedRacks_nulls,
    SUM(CASE WHEN [FREE_RACKS] IS NULL THEN 1 ELSE 0 END) AS FreeRacks_nulls
FROM dbo.DallasToWashingtonILAData;

-- Negative or zero MRR in quotes
SELECT *
FROM dbo.SalesQuotingData
WHERE [MONTHLY RECURRING REVENUE] <= 0;
